"""
Django settings for backup_system project.

Generated by 'django-admin startproject' using Django 5.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!%z9+rx7(3)_^!!)9=#sypp-bc^0ehe7)o)r+$$z2*4$%l+b))'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.localhost']  # The .localhost will match all subdomains


# Application definition

INSTALLED_APPS = [
    'django_tenants',# Must be before django.contrib.contenttypes
    'tenants'  ,                # Your tenant app
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
     'rest_framework',
     'rest_framework_simplejwt',
     'corsheaders',
     'drf_yasg',
     'django_celery_beat',
     'django_filters',
     'django_extensions',
     'storages',
     'django_redis',
     "django_celery_results",
     # Project apps
     'accounts',
     'jobs', # Assuming 'jobs' is a tenant-specific app
    
]


# Multi-tenancy configuration
# Define SHARED_APPS first, as TENANT_APPS might reference it implicitly or for clarity
SHARED_APPS = [
    'django_tenants',  # mandatory
    'django.contrib.contenttypes',
    'django.contrib.auth', # User model is in public schema
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin', # Admin for the public schema

    # Your custom apps that should reside in the public schema
    'accounts', # Your User model is here
    'tenants',  # App where Tenant and Domain models are defined

    # Third-party apps that are shared
    'rest_framework',
    'rest_framework_simplejwt', # Assuming this is shared
    'corsheaders',
    'drf_yasg',
    'django_celery_beat',
    'django_filters',
    'django_extensions',
    'storages',
    'django_redis',
    "django_celery_results",
    
]

TENANT_MODEL = "tenants.Tenant"
TENANT_DOMAIN_MODEL = "tenants.Domain"
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

TENANT_APPS = [
    # Apps specific to each tenant
    'django.contrib.contenttypes', # Often needed by tenant apps
    # 'django.contrib.auth', # REMOVE - User model is shared
    # 'django.contrib.admin', # Add only if you want a separate admin site per tenant,
                              # distinct from the public one. Usually, one admin site is enough.
    # 'django.contrib.sites', # Usually shared
    # 'django.contrib.sessions', # Usually shared
    # 'django.contrib.messages', # Usually shared
    # 'django.contrib.staticfiles', # Usually shared

    #'accounts', # REMOVE - User model is shared
    'jobs',
    'backrest', # Assuming 'jobs' is a tenant-specific app
    # Add other tenant-specific apps here
]
BACKREST_API_URL = 'http://localhost:9898'
# Ensure INSTALLED_APPS is correctly constructed
# It should include all SHARED_APPS and all TENANT_APPS without duplication
# A common pattern:
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

# Ensure 'django.contrib.auth' and 'accounts' are NOT in the TENANT_APPS list that gets processed
# for tenant-specific migrations if they are truly shared.
# The INSTALLED_APPS construction above should handle this if SHARED_APPS and TENANT_APPS are defined correctly.

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_tenants.middleware.main.TenantMainMiddleware', # Should be high up
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backup_system.urls'
PUBLIC_SCHEMA_URLCONF = 'backup_system.urls'
# CORS Configuration
# for linking the angular front
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200", # Your Angular dev server
    # Add your production frontend URL here later
]



# Configuration for Persistent Ansible Controller
#ANSIBLE_CONTAINER_NAME = "focused_yalow"
#HOST_SHARED_ANSIBLE_RUN_DIR = r"C:\Users\defin\WCTPROJECTMVP6.0\backend\ansible\ansible_shared_data" # Raw string for Windows paths
#CONTAINER_PLAYBOOKS_DIR = "/opt/ansible_playbooks"
#CONTAINER_SHARED_ANSIBLE_RUN_DIR = "/opt/ansible_run_data"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backup_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'djangobackend', #change it databasename
        'USER': 'postgres', #change it database user name
        'PASSWORD': 'postgres', # change user database password
        'HOST': 'localhost',  
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PUBLIC_SCHEMA_NAME = 'public'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# Add STATIC_ROOT for collectstatic if needed for production
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Use the custom authentication class
        'accounts.authentication.PublicSchemaJWTAuthentication',
        # You might keep others if needed, but this should be primary for JWT
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
  
}

# Simple JWT Settings (customize lifetimes, etc.)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), # Adjust as needed
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Use Django's secret key for signing
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

AUTHENTICATION_BACKENDS = [
    'accounts.authentication.EmailOrUsernameLoginBackend',
    # 'django.contrib.auth.backends.ModelBackend', # You might want to remove or keep the default
                                                  # depending on if you need it for other purposes (e.g. Django admin direct login).
                                                  # For the main app login, our custom backend should suffice.
                                                  # If kept, ensure the order is considered. For this specific login requirement,
                                                  # relying solely on the custom backend is cleaner.
]

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'