# Generated by Django 5.1.9 on 2025-06-04 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backrest', '0002_server_backrest_instance_id'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backrestoperation',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When this operation is scheduled to run', null=True),
        ),
        migrations.CreateModel(
            name='BackrestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('logger_name', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(help_text='Source of the log (file path)', max_length=255)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backrest.server')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='backrest_ba_timesta_d61484_idx'), models.Index(fields=['level'], name='backrest_ba_level_4dc110_idx'), models.Index(fields=['server'], name='backrest_ba_server__e57422_idx')],
            },
        ),
    ]
