# Generated by Django 5.1.9 on 2025-06-06 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backrest', '0003_backrestoperation_scheduled_at_backrestlog'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackrestInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100)),
                ('install_path', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=9898)),
                ('is_active', models.BooleanField(default=True)),
                ('setup_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='backrest.server')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backrest_instances', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'instance_id')},
            },
        ),
    ]
